import { auth } from '@/auth';
import ClientProviders from '@/providers';
import '@worldcoin/mini-apps-ui-kit-react/styles.css';
import { Geist, Geist_Mono } from 'next/font/google';
import { jsx as _jsx } from 'react/jsx-runtime';
import './globals.css';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});
export const metadata = {
  title: 'Template Mini App',
  description: 'Generated by create next app',
};
export default async function RootLayout({ children }) {
  const session = await auth();
  return _jsx('html', {
    lang: 'en',
    children: _jsx('body', {
      className: `${geistSans.variable} ${geistMono.variable} `,
      children: _jsx(ClientProviders, { session: session, children: children }),
    }),
  });
}
