import { auth } from '@/auth';
import ClientProviders from '@/components/ClientProviders';
import { Inter } from 'next/font/google';
import { jsx as _jsx } from 'react/jsx-runtime';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default async function RootLayout({ children }) {
  const session = await auth();
  return _jsx('html', {
    lang: 'en',
    children: _jsx('body', {
      className: inter.className,
      children: _jsx(ClientProviders, { session: session, children: children }),
    }),
  });
}
